steps:
  # Build the image using Dockerfile
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}", "."]

  # Push the built image to the container registry service
  - id: "push image to Container Registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}"]

   # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
     - run
     - deploy
     - ${_SERVICE_NAME}
     - --allow-unauthenticated
     - --image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}
     - --port=8080
     - --region=${_REGION}

# Here are the substitution variables related to the services.
substitutions:
  _REGION: us-central1 # The region where the cloud services are located.
  _SERVICE_NAME: node-gcp-service # The name of the App Cloud Run service (Any name you choose).
